version: '3'

services:
  # Frontend
  web:
    image: jitsi/web
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    volumes:
      - jitsimeet_web_web:/config
    env_file:
      - ./settings.env
    networks:
      - jitsi

  # XMPP server
  prosody:
    image: jitsi/prosody
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - jitsimeet_prosody:/config
    env_file:
      - ./settings.env
    networks:
      - jitsi

  # Focus component
  jicofo:
    image: jitsi/jicofo
    volumes:
      - jitsimeet_jicofo:/config
      - ./settings.env
    env_file:
      - ./settings.env
    depends_on:
      - prosody
    networks:
      - jitsi

  # Video bridge
  jvb:
    image: jitsi/jvb
    ports:
      - '${JVB_PORT}:${JVB_PORT}/udp'
      - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
    volumes:
      - jitsimeet_jvb:/config
    env_file:
      - ./settings.env
    depends_on:
      - prosody
    networks:
      - jitsi

# Custom network so all services can communicate using a FQDN
networks:
    jitsimeet:
