version: '3'

services:
  # Frontend
  web:
    image: jitsi/web:${JITSI_IMAGE_VERSION:-stable-9457-2}
    restart: always
    ports:
      - '8397:80'
      - '8443:443'
    env_file:
      - ./settings.env
    networks:
      meet.jitsi:

  # XMPP server
  prosody:
    image: jitsi/prosody:${JITSI_IMAGE_VERSION:-stable-9457-2}
    restart: always
    ports:
      - '5222:5222'
      - '5347:5347'
      - '5280:5280'
    env_file:
      - ./settings.env
    networks:
      meet.jitsi:
        aliases:
          - xmpp.meet.jitsi

  # Focus component
  jicofo:
    image: jitsi/jicofo:${JITSI_IMAGE_VERSION:-stable-9457-2}
    restart: always
    env_file:
      - ./settings.env
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  # Video bridge
  jvb:
    image: jitsi/jvb:${JITSI_IMAGE_VERSION:-stable-9457-2}
    restart: always
    ports:
      - '10000:10000/udp'
      - '4443:4443'
    env_file:
      - ./settings.env
    depends_on:
      - prosody
    networks:
      meet.jitsi:

# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
