version: '3'

services:
  # Frontend
  web:
    image: jitsi/web
    ports:
      - '8000:80'
      - '8443:443'
    volumes:
      - jitsimeet_web_web:/config
    env_file:
      - ./settings.env
    networks:
      - jitsi

  # XMPP server
  prosody:
    image: jitsi/prosody
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - jitsimeet_prosody:/config
    env_file:
      - ./settings.env
    networks:
      - jitsi

  # Focus component
  jicofo:
    image: jitsi/jicofo
    volumes:
      - jitsimeet_jicofo:/config
    env_file:
      - ./settings.env
    depends_on:
      - prosody
    networks:
      - jitsi

  # Video bridge
  jvb:
    image: jitsi/jvb
    ports:
      - '10000:10000/udp'
      - '4443:4443'
    volumes:
      - jitsimeet_jvb:/config
    env_file:
      - ./settings.env
    depends_on:
      - prosody
    networks:
      - jitsi

# Custom network so all services can communicate using a FQDN
networks:
    jitsimeet:
